apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: type-3
  name: e2e
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: e2e
              image: cr.yandex/crpjhav5dledksn6gaeo/labkeeper-e2e:latest
              imagePullPolicy: Always
              env:
                - name: E2E_HOST
                  value: https://labkeeper.io
                - name: E2E_TELEGRAM_BOT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: type_3_e2e_bot_token
                      name: type-3-e2e-secrets
                - name: E2E_TELEGRAM_CHAT_ID
                  valueFrom:
                    secretKeyRef:
                      key: type_3_e2e_chat_id
                      name: type-3-e2e-secrets
          restartPolicy: OnFailure
