apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: type-3-test
  name: e2e
spec:
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: e2e
              image: cr.yandex/crpjhav5dledksn6gaeo/labkeeper-e2e:latest
              imagePullPolicy: Always
              env:
                - name: E2E_HOST
                  value: https://labkeeper.io
                - name: E2E_TELEGRAM_BOT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: type_3_e2e_bot_token
                      name: type-3-e2e-secrets
                - name: E2E_TELEGRAM_CHAT_ID
                  valueFrom:
                    secretKeyRef:
                      key: type_3_e2e_chat_id
                      name: type-3-e2e-secrets
                - name: E2E_CAPTCHA_BYPASS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: type_3_e2e_captcha_bypass_token
                      name: type-3-e2e-secrets
                - name: E2E_USER_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: type_3_e2e_user_password
                      name: type-3-e2e-secrets
                - name: E2E_USER_EMAIL
                  valueFrom:
                    secretKeyRef:
                      key: type_3_e2e_user_email
                      name: type-3-e2e-secrets
          restartPolicy: Never
