apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: type-3
  name: e2e
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: e2e
              image: cr.yandex/crpjhav5dledksn6gaeo/labkeeper-e2e:latest
              imagePullPolicy: Always
              env:
                - name: E2E_HOST
                  value: https://labkeeper.io
          restartPolicy: OnFailure
