name: Playwright Tests
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: redhat-actions/podman-login@v1
      with:
        registry: cr.yandex/crpjhav5dledksn6gaeo
        username: oauth
        password: ${{ secrets.YC_DOCKER_REGISTRY_TOKEN }}
    - uses: redhat-actions/buildah-build@v2
      with:
        image: labkeeper-e2e
        tags: latest
        containerfiles: ./Dockerfile
    - uses: redhat-actions/push-to-registry@v2
      with:
        image: labkeeper-e2e
        tags: latest
        registry: cr.yandex/crpjhav5dledksn6gaeo
        username: oauth
        password: ${{ secrets.YC_DOCKER_REGISTRY_TOKEN }}
    - shell: bash
      run: |
        kubectl config set-cluster k8s --server=${{ secrets.KUBERNETES_URL }} --insecure-skip-tls-verify=true
        kubectl config set-credentials admin --token=${{ secrets.KUBERNETES_SECRET }}
        kubectl config set-context default --cluster=k8s --user=admin
        kubectl config use-context default
        kubectl get pod -A
    - name: Deploy to Kubernetes
      shell: bash
      run: |
        kubectl delete --ignore-not-found=true -f ./scripts/k8s/cronJob.yaml
        kubectl apply -f ./scripts/k8s/cronJob.yaml
        kubectl -n type-3-test create job e2e-test-startup --from=cronjob/e2e
